// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofGEE9v_e3cHnvkSN5_elw_XvnJfKnDA',
    appId: '1:108946371041:android:34bbdfb083b1d57932e2a0',
    messagingSenderId: '108946371041',
    projectId: 'project-2-eead4',
    storageBucket: 'project-2-eead4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbchfq-perV5MWK9fh-BIUks9uI-dKe_0',
    appId: '1:108946371041:ios:13a8e9036a04717b32e2a0',
    messagingSenderId: '108946371041',
    projectId: 'project-2-eead4',
    storageBucket: 'project-2-eead4.appspot.com',
    androidClientId: '108946371041-2qf41efrnbfc382tgtfm1d05lsj2s8tb.apps.googleusercontent.com',
    iosClientId: '108946371041-s2r60u90uiu3a0mgfrtjdaua0ujjk37t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
